platform :ios, '12.0'
use_frameworks! linkage: :static

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end



target 'Nova_Example' do
  pod 'NovaMetrics', path: '../', :testspecs => ['Tests'], subspecs: [
    'AnrMonitorPlugin',
    'PageMonitorPlugin',
    'MemoryLeaksPlugin',
    'UIThreadMonitorPlugin',
  ]
  pod 'NovaUI', path: '../', :testspecs => ['Tests']
end
